name: flower_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  archive: ^3.3.6
  cupertino_icons: ^1.0.2
  dart_flower: 
    path: ../
  dio: ^5.0.0
  flutter: 
    sdk: flutter
  get: 4.6.5
  image_picker: 0.8.6+4
  intl:
  path_provider: ^2.0.12
  permission_handler: ^10.2.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  lint: ^2.0.1


flutter: 
  uses-material-design: true
  assets:
      - assets/data/
