name: dart_flower
description: A simple FLOWER client written in dart
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
dependencies:
  fixnum: ^1.1.0
  grpc: ^3.1.0
  logging: ^1.1.1
  protobuf: ^2.1.0
